// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf24aurXuKOui4bqNU14bCzw2c_DRKO8o',
    appId: '1:983215134977:web:24cb16da67986045286300',
    messagingSenderId: '983215134977',
    projectId: 'singin-signup-6b7fb',
    authDomain: 'singin-signup-6b7fb.firebaseapp.com',
    storageBucket: 'singin-signup-6b7fb.firebasestorage.app',
    measurementId: 'G-DTXSXQ2CNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WhPKxUABAH-aZc9eWsgHxliS0T-VBcg',
    appId: '1:983215134977:android:087976f1a212e0b4286300',
    messagingSenderId: '983215134977',
    projectId: 'singin-signup-6b7fb',
    storageBucket: 'singin-signup-6b7fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7KLurXjUYLbTgEaZFcmxDfeAAY09dr-o',
    appId: '1:983215134977:ios:82633b5fb067bc8c286300',
    messagingSenderId: '983215134977',
    projectId: 'singin-signup-6b7fb',
    storageBucket: 'singin-signup-6b7fb.firebasestorage.app',
    androidClientId: '983215134977-v60lu2s31shtgik3fu8it85bimjritjf.apps.googleusercontent.com',
    iosClientId: '983215134977-up6ldq6hh7e7mtpg6qrvc885v370fk5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7KLurXjUYLbTgEaZFcmxDfeAAY09dr-o',
    appId: '1:983215134977:ios:82633b5fb067bc8c286300',
    messagingSenderId: '983215134977',
    projectId: 'singin-signup-6b7fb',
    storageBucket: 'singin-signup-6b7fb.firebasestorage.app',
    androidClientId: '983215134977-v60lu2s31shtgik3fu8it85bimjritjf.apps.googleusercontent.com',
    iosClientId: '983215134977-up6ldq6hh7e7mtpg6qrvc885v370fk5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf24aurXuKOui4bqNU14bCzw2c_DRKO8o',
    appId: '1:983215134977:web:45fb142020f1e3e9286300',
    messagingSenderId: '983215134977',
    projectId: 'singin-signup-6b7fb',
    authDomain: 'singin-signup-6b7fb.firebaseapp.com',
    storageBucket: 'singin-signup-6b7fb.firebasestorage.app',
    measurementId: 'G-8W774WXB8T',
  );

}